version: '3.9'

services:
    weblog:
        build: .
        command: python /code/manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/code
        ports:
            - 8000:8000
        depends_on:
            - db
        environment:
            - "DJANGO_SECRET_KEY=django-insecure-s%*$422fne^66-p3txr)67ee&s4m3h&+@%p2n&wd#%dm7q9k2&"
            - "DJANGO_DEBUG=True"
    
    db:
        image: postgres
        volumes:
            - postgres_data:/var/lib/postgresql/data
        environment:
            - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
    postgres_data: